#!/bin/bash


# Startup script to call at OS startup


#----- Daemons
    # Auto USB mounter
        /usr/bin/udiskie -s &
    # Disale touchpad while typing on keyboard
        syndaemon -i 0.2 -d &
    # Start pulseaudio
    #FIXME: Do not know why it doesn't work without starting and killing it first
        pulseaudio --start && pulseaudio --kill && pulseaudio --statrt
    # Notifications daemon
        dunst &

#----- Tray icons
    # Network manager with tray icon
        nm-applet 2>&1 /dev/null &
    # Pulse audi tray icon
        pasystray &

#----- Settings
    # Invert caps lock key and escape key
        setxkbmap -option caps:escape
    # Disable screen blanking when inactive
        xset -dpms & xset s noblank & xset s off
